root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/main.go ./cmd/main.go"
bin = "./bin/main.go"
full_bin = "bin/main.go"

include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "bin"]
delay = 1000
stop_on_error = true